Pair Programming

Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [35]:
import numpy as np

In [36]:
array1= np.random.randint(10,100, (50))
array1

array([22, 92, 26, 34, 60, 78, 82, 73, 27, 80, 10, 49, 90, 68, 86, 86, 18,
       55, 73, 31, 54, 56, 33, 56, 48, 46, 26, 60, 44, 76, 69, 67, 85, 82,
       19, 32, 60, 31, 96, 45, 64, 78, 82, 76, 26, 76, 68, 97, 22, 98])

In [37]:
print(array1[::5])

[22 78 10 86 54 46 69 32 64 76]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [38]:
array2 = np.random.randint(1,21, (30))
array2

array([ 7, 19, 10, 10,  4, 14,  9, 15, 10,  7, 18, 16, 18,  8,  8, 18, 12,
        9, 13,  8, 10,  5,  5, 15, 17,  3,  7, 10, 11,  3])

In [39]:
print(array2[1::2])

[19 10 14 15  7 16  8 18  9  8  5 15  3 10  3]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [40]:
array3= np.random.uniform(1, 10, (4,6))
array3

array([[2.42616059, 9.44560046, 1.72420228, 2.69610085, 6.24727712,
        4.77360422],
       [9.9724045 , 5.9244266 , 6.10472117, 9.32660926, 3.77148484,
        3.99108969],
       [7.27571989, 9.24588312, 9.30390501, 1.37435551, 6.70784058,
        2.14310714],
       [1.63787645, 1.58118686, 8.58425725, 8.33397999, 1.29349584,
        9.49714804]])

In [41]:
array3_=np.round(array3,2)

In [42]:
print(array3_)

[[2.43 9.45 1.72 2.7  6.25 4.77]
 [9.97 5.92 6.1  9.33 3.77 3.99]
 [7.28 9.25 9.3  1.37 6.71 2.14]
 [1.64 1.58 8.58 8.33 1.29 9.5 ]]


In [43]:
print(array3_[-1])

[1.64 1.58 8.58 8.33 1.29 9.5 ]


4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

In [44]:
array4 = np.random.rand(6,4)
array4

array([[0.90905074, 0.80122155, 0.77372752, 0.34382623],
       [0.69405066, 0.00125046, 0.01318129, 0.83607767],
       [0.05452131, 0.98457196, 0.20952981, 0.69167427],
       [0.85447794, 0.94556775, 0.659746  , 0.27597029],
       [0.92537657, 0.45820493, 0.99776237, 0.67804739],
       [0.80548478, 0.28897035, 0.96141213, 0.31450649]])

In [45]:
array4_=np.round(array4,2)

In [46]:
print(array4_)

[[0.91 0.8  0.77 0.34]
 [0.69 0.   0.01 0.84]
 [0.05 0.98 0.21 0.69]
 [0.85 0.95 0.66 0.28]
 [0.93 0.46 1.   0.68]
 [0.81 0.29 0.96 0.31]]


In [47]:
print(array4_[:,1])

[0.8  0.   0.98 0.95 0.46 0.29]


5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [48]:
array5= np.random.randint(-50, 50, (30))
print(array5)

[-44   5  -8 -23 -10  10 -24 -28  12  36 -49 -29 -14  48  27  45 -11 -37
  35  40 -50  44  20 -22   1 -33 -23 -22  32  31]


In [49]:
n_nega= array5[array5 <0]

In [50]:
print(n_nega)

[-44  -8 -23 -10 -24 -28 -49 -29 -14 -11 -37 -50 -22 -33 -23 -22]


6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [51]:
array6 = np.random.rand(10)
array6

array([0.06340485, 0.68371356, 0.01775237, 0.66106103, 0.72047196,
       0.82818719, 0.33808984, 0.49620345, 0.5170526 , 0.65153652])

In [52]:
array6=np.round(array6,2)
array6

array([0.06, 0.68, 0.02, 0.66, 0.72, 0.83, 0.34, 0.5 , 0.52, 0.65])

In [53]:
elemento= array6[array6 > 0.5]
elemento

array([0.68, 0.66, 0.72, 0.83, 0.52, 0.65])

In [54]:
posiciones= np.where(array6 > 0.5)
posiciones

(array([1, 3, 4, 5, 8, 9]),)

Reshape y Transpose:

Ejercicios con reshape:
Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [55]:
array7= np.random.randint(1, 101, (2,3,4))
array7

array([[[85, 78, 73, 85],
        [19, 10, 84, 96],
        [22, 66, 66, 14]],

       [[98, 45,  9, 86],
        [26, 65, 90, 44],
        [63, 64, 53, 53]]])

In [56]:
array7_bis= array7.reshape(4,6)
array7_bis

array([[85, 78, 73, 85, 19, 10],
       [84, 96, 22, 66, 66, 14],
       [98, 45,  9, 86, 26, 65],
       [90, 44, 63, 64, 53, 53]])

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [57]:
array8= np.random.randint(1,60, (3,4,5))
array8

array([[[48,  8, 18, 50, 41],
        [37, 36, 29, 29,  7],
        [42, 11, 13, 15, 51],
        [16, 53, 38, 28, 53]],

       [[53, 13, 51, 52, 38],
        [38, 47,  7, 25,  9],
        [20, 36, 14, 50,  4],
        [26, 29,  6, 23, 44]],

       [[25, 43, 44, 16, 10],
        [53, 55, 48,  5,  8],
        [33, 59,  8, 42, 58],
        [31, 43, 44, 55, 30]]])

In [58]:
array8_bis= np.reshape(array8, (6,10))
array8_bis

array([[48,  8, 18, 50, 41, 37, 36, 29, 29,  7],
       [42, 11, 13, 15, 51, 16, 53, 38, 28, 53],
       [53, 13, 51, 52, 38, 38, 47,  7, 25,  9],
       [20, 36, 14, 50,  4, 26, 29,  6, 23, 44],
       [25, 43, 44, 16, 10, 53, 55, 48,  5,  8],
       [33, 59,  8, 42, 58, 31, 43, 44, 55, 30]])

3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [59]:
array9= np.random.rand(4,3,2)
array9

array([[[0.62479515, 0.4099799 ],
        [0.13463254, 0.84245336],
        [0.70523332, 0.08089042]],

       [[0.2867233 , 0.72060405],
        [0.91525392, 0.99286805],
        [0.5429547 , 0.81612067]],

       [[0.98776584, 0.10175106],
        [0.20885285, 0.15187563],
        [0.47740777, 0.65402993]],

       [[0.18831034, 0.77316339],
        [0.3976648 , 0.60061987],
        [0.70620306, 0.54184518]]])

In [60]:
array9_bis= array9.reshape(6,4)
array9_bis

array([[0.62479515, 0.4099799 , 0.13463254, 0.84245336],
       [0.70523332, 0.08089042, 0.2867233 , 0.72060405],
       [0.91525392, 0.99286805, 0.5429547 , 0.81612067],
       [0.98776584, 0.10175106, 0.20885285, 0.15187563],
       [0.47740777, 0.65402993, 0.18831034, 0.77316339],
       [0.3976648 , 0.60061987, 0.70620306, 0.54184518]])

Ejercicios con transpose:
4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [61]:
array8

array([[[48,  8, 18, 50, 41],
        [37, 36, 29, 29,  7],
        [42, 11, 13, 15, 51],
        [16, 53, 38, 28, 53]],

       [[53, 13, 51, 52, 38],
        [38, 47,  7, 25,  9],
        [20, 36, 14, 50,  4],
        [26, 29,  6, 23, 44]],

       [[25, 43, 44, 16, 10],
        [53, 55, 48,  5,  8],
        [33, 59,  8, 42, 58],
        [31, 43, 44, 55, 30]]])

In [62]:
array8_nuevo= np.transpose(array8)
array8_nuevo

array([[[48, 53, 25],
        [37, 38, 53],
        [42, 20, 33],
        [16, 26, 31]],

       [[ 8, 13, 43],
        [36, 47, 55],
        [11, 36, 59],
        [53, 29, 43]],

       [[18, 51, 44],
        [29,  7, 48],
        [13, 14,  8],
        [38,  6, 44]],

       [[50, 52, 16],
        [29, 25,  5],
        [15, 50, 42],
        [28, 23, 55]],

       [[41, 38, 10],
        [ 7,  9,  8],
        [51,  4, 58],
        [53, 44, 30]]])

5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

In [63]:
array9_transpose= np.transpose(array9, (1,2,0))
array9_transpose

array([[[0.62479515, 0.2867233 , 0.98776584, 0.18831034],
        [0.4099799 , 0.72060405, 0.10175106, 0.77316339]],

       [[0.13463254, 0.91525392, 0.20885285, 0.3976648 ],
        [0.84245336, 0.99286805, 0.15187563, 0.60061987]],

       [[0.70523332, 0.5429547 , 0.47740777, 0.70620306],
        [0.08089042, 0.81612067, 0.65402993, 0.54184518]]])

Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [64]:
array10= np.random.rand(2,3,5).round(1)
array10

array([[[0.4, 0.2, 0.9, 0.9, 0.6],
        [0.4, 0.7, 0.2, 0.2, 0.9],
        [0.3, 0.7, 0.6, 0.5, 0.9]],

       [[0.9, 0.6, 1. , 0.3, 1. ],
        [0.8, 0. , 0.8, 0.9, 0.2],
        [0.6, 0.1, 0. , 0.3, 0.3]]])


Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".

Si el valor del array es mayor que la media, se reemplaza por "B".

Si el valor del array es menor que la media, se reemplaza por "C".

Si el valor es igual que el máximo, se reemplaza por "D".

Si el valor es igual que el mínimo, se reemplaza por "E".

In [65]:
#calculos 
media = np.mean(array10)
max = np.max(array10)
min = np.min(array10)

In [66]:
# Crea un nuevo array vacío con la misma forma y tipo que el array "arr"
# pero con el tipo de dato "str" para cada elemento.
vacio = np.empty_like(array10, dtype=str) 
vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [67]:
for matriz in range(array10.shape[0]): # Recorre cada fila del array "arr"
    for fila in range(array10.shape[1]): # Recorre cada columna del array "arr"
        for col in range(array10.shape[2]): # Recorre cada capa del array "arr"
            # Si el valor actual es igual a la media, se asigna "A" al array vacío
            if array10[matriz][fila][col] == media:
                vacio[matriz][fila][col] = "A"

            # Si el valor actual es igual al máximo, se asigna "D" al array vacío
            elif array10[matriz][fila][col] == max:
                vacio[matriz][fila][col] = "D"

            # Si el valor actual es igual al mínimo, se asigna "E" al array vacío
            elif array10[matriz][fila][col] == min:
                vacio[matriz][fila][col] = "E"

            # Si el valor actual es mayor que la media, se asigna "B" al array vacío
            elif array10[matriz][fila][col] > media:
                vacio[matriz][fila][col] = "B"

            # Si el valor actual es menor que la media, se asigna "C" al array vacío
            elif array10[matriz][fila][col] < media:
                vacio[matriz][fila][col] = "C"

In [68]:
vacio

array([[['C', 'C', 'B', 'B', 'B'],
        ['C', 'B', 'C', 'C', 'B'],
        ['C', 'B', 'B', 'C', 'B']],

       [['B', 'B', 'D', 'C', 'D'],
        ['B', 'E', 'B', 'B', 'C'],
        ['B', 'C', 'E', 'C', 'C']]], dtype='<U1')