Pair Programming

Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [2]:
import numpy as np

In [3]:
array1= np.random.randint(10,100, (50))
array1

array([58, 42, 13, 95, 55, 33, 44, 23, 81, 76, 58, 68, 50, 52, 15, 15, 30,
       15, 18, 32, 39, 55, 27, 38, 49, 14, 40, 24, 64, 21, 73, 87, 63, 87,
       92, 55, 96, 74, 69, 22, 76, 85, 55, 63, 83, 86, 39, 52, 21, 33])

In [4]:
print(array1[::5])

[58 33 58 15 39 14 73 55 76 86]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [6]:
array2 = np.random.randint(1,21, (30))
array2

array([14, 11, 12, 10,  8, 11,  9, 14,  5,  8,  5,  3,  9, 12,  7, 19, 10,
       20, 17, 11,  5,  1, 18, 20, 13, 14, 11, 17, 11,  1])

In [7]:
print(array2[1::2])

[11 10 11 14  8  3 12 19 20 11  1 20 14 17  1]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [8]:
array3= np.random.uniform(1, 10, (4,6))
array3

array([[4.06854312, 4.98450963, 5.96250405, 8.22045274, 4.03591321,
        5.61649052],
       [9.06945642, 1.13230097, 6.43779509, 1.78360343, 8.37894128,
        1.47353113],
       [4.02533356, 6.88568476, 7.49751168, 8.6075854 , 1.56930894,
        9.18974197],
       [6.46276773, 7.03295845, 9.03930238, 8.59111294, 9.65329238,
        9.42861357]])

In [13]:
array3_=np.round(array3,2)

In [14]:
print(array3_)

[[4.07 4.98 5.96 8.22 4.04 5.62]
 [9.07 1.13 6.44 1.78 8.38 1.47]
 [4.03 6.89 7.5  8.61 1.57 9.19]
 [6.46 7.03 9.04 8.59 9.65 9.43]]


In [15]:
print(array3_[-1])

[6.46 7.03 9.04 8.59 9.65 9.43]


4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

In [16]:
array4 = np.random.rand(6,4)
array4

array([[0.06422455, 0.40627862, 0.83360346, 0.04589213],
       [0.89495967, 0.88260461, 0.25361269, 0.61298731],
       [0.72200055, 0.15259508, 0.11284015, 0.84406462],
       [0.92926915, 0.33967836, 0.93132952, 0.22585805],
       [0.27908675, 0.47841388, 0.05284117, 0.36424732],
       [0.18626695, 0.84035137, 0.95084549, 0.26918356]])

In [17]:
array4_=np.round(array4,2)

In [18]:
print(array4_)

[[0.06 0.41 0.83 0.05]
 [0.89 0.88 0.25 0.61]
 [0.72 0.15 0.11 0.84]
 [0.93 0.34 0.93 0.23]
 [0.28 0.48 0.05 0.36]
 [0.19 0.84 0.95 0.27]]


In [20]:
print(array4_[:,1])

[0.41 0.88 0.15 0.34 0.48 0.84]


5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [22]:
array5= np.random.randint(-50, 50, (30))
print(array5)

[ 21  31 -48 -32  35  28  33  12   0  28 -17 -23 -10  28   4  36 -15   6
 -39 -21   8  48 -23   1  13 -32  -4  11 -28  14]


In [24]:
n_nega= array5[array5 <0]

In [25]:
print(n_nega)

[-48 -32 -17 -23 -10 -15 -39 -21 -23 -32  -4 -28]


6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [26]:
array6 = np.random.rand(10)
array6

array([0.21772798, 0.24408227, 0.62568698, 0.62694143, 0.69113736,
       0.03275488, 0.4059397 , 0.11891737, 0.40826076, 0.93893535])

In [29]:
array6=np.round(array6,2)
array6

array([0.22, 0.24, 0.63, 0.63, 0.69, 0.03, 0.41, 0.12, 0.41, 0.94])

In [30]:
elemento= array6[array6 > 0.5]
elemento

array([0.63, 0.63, 0.69, 0.94])

In [31]:
posiciones= np.where(array6 > 0.5)
posiciones

(array([2, 3, 4, 9]),)

Reshape y Transpose:

Ejercicios con reshape:
Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [32]:
array7= np.random.randint(1, 101, (2,3,4))
array7

array([[[ 88,  13,  81,  75],
        [  9,  90,  19,  37],
        [ 10,  19,   3,  91]],

       [[ 78, 100,   3,  26],
        [ 78,  65,  82,  90],
        [ 28,  50,  37,   7]]])

In [33]:
array7_bis= array7.reshape(4,6)
array7_bis

array([[ 88,  13,  81,  75,   9,  90],
       [ 19,  37,  10,  19,   3,  91],
       [ 78, 100,   3,  26,  78,  65],
       [ 82,  90,  28,  50,  37,   7]])

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [35]:
array8= np.random.randint(1,60, (3,4,5))
array8

array([[[ 4,  7, 47,  9, 27],
        [34, 46, 52, 48, 52],
        [43, 22, 36, 30, 43],
        [22, 24, 49, 51, 48]],

       [[36, 45, 45, 23, 56],
        [ 6, 17, 12, 32, 38],
        [ 6, 53, 52, 49, 33],
        [32, 37,  2, 23,  4]],

       [[29, 26, 27, 19, 57],
        [ 8, 50, 44, 16, 36],
        [46, 27, 11, 38, 37],
        [51, 55, 31, 40, 26]]])

In [37]:
array8_bis= np.reshape(array8, (6,10))
array8_bis

array([[ 4,  7, 47,  9, 27, 34, 46, 52, 48, 52],
       [43, 22, 36, 30, 43, 22, 24, 49, 51, 48],
       [36, 45, 45, 23, 56,  6, 17, 12, 32, 38],
       [ 6, 53, 52, 49, 33, 32, 37,  2, 23,  4],
       [29, 26, 27, 19, 57,  8, 50, 44, 16, 36],
       [46, 27, 11, 38, 37, 51, 55, 31, 40, 26]])

3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [38]:
array9= np.random.rand(4,3,2)
array9

array([[[0.4172722 , 0.03951582],
        [0.15623245, 0.1638901 ],
        [0.94939288, 0.47203401]],

       [[0.52410796, 0.63104471],
        [0.73445472, 0.30362681],
        [0.29584608, 0.22406058]],

       [[0.74275629, 0.5913752 ],
        [0.12893475, 0.76602946],
        [0.65437785, 0.79421562]],

       [[0.30547426, 0.4935739 ],
        [0.45826277, 0.62501702],
        [0.53550188, 0.49859871]]])

In [39]:
array9_bis= array9.reshape(6,4)
array9_bis

array([[0.4172722 , 0.03951582, 0.15623245, 0.1638901 ],
       [0.94939288, 0.47203401, 0.52410796, 0.63104471],
       [0.73445472, 0.30362681, 0.29584608, 0.22406058],
       [0.74275629, 0.5913752 , 0.12893475, 0.76602946],
       [0.65437785, 0.79421562, 0.30547426, 0.4935739 ],
       [0.45826277, 0.62501702, 0.53550188, 0.49859871]])

Ejercicios con transpose:
4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [40]:
array8

array([[[ 4,  7, 47,  9, 27],
        [34, 46, 52, 48, 52],
        [43, 22, 36, 30, 43],
        [22, 24, 49, 51, 48]],

       [[36, 45, 45, 23, 56],
        [ 6, 17, 12, 32, 38],
        [ 6, 53, 52, 49, 33],
        [32, 37,  2, 23,  4]],

       [[29, 26, 27, 19, 57],
        [ 8, 50, 44, 16, 36],
        [46, 27, 11, 38, 37],
        [51, 55, 31, 40, 26]]])

In [42]:
array8_nuevo= np.transpose(array8)
array8_nuevo

array([[[ 4, 36, 29],
        [34,  6,  8],
        [43,  6, 46],
        [22, 32, 51]],

       [[ 7, 45, 26],
        [46, 17, 50],
        [22, 53, 27],
        [24, 37, 55]],

       [[47, 45, 27],
        [52, 12, 44],
        [36, 52, 11],
        [49,  2, 31]],

       [[ 9, 23, 19],
        [48, 32, 16],
        [30, 49, 38],
        [51, 23, 40]],

       [[27, 56, 57],
        [52, 38, 36],
        [43, 33, 37],
        [48,  4, 26]]])

5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

In [43]:
array9_transpose= np.transpose(array9, (1,2,0))
array9_transpose

array([[[0.4172722 , 0.52410796, 0.74275629, 0.30547426],
        [0.03951582, 0.63104471, 0.5913752 , 0.4935739 ]],

       [[0.15623245, 0.73445472, 0.12893475, 0.45826277],
        [0.1638901 , 0.30362681, 0.76602946, 0.62501702]],

       [[0.94939288, 0.29584608, 0.65437785, 0.53550188],
        [0.47203401, 0.22406058, 0.79421562, 0.49859871]]])

Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [44]:
array10= np.random.rand(2,3,5).round(1)
array10

array([[[0.8, 0.4, 0. , 0.3, 0. ],
        [0. , 1. , 0. , 0.8, 0.1],
        [0.3, 0.1, 0.1, 0.4, 1. ]],

       [[0.6, 0.3, 0.8, 0.9, 0.6],
        [0.6, 0.2, 0.6, 0.4, 0.1],
        [0.9, 0. , 0.5, 0.8, 0.1]]])

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".

In [46]:
array11= np.empty((2,3,5))
array11

array([[[0.8, 0.4, 0. , 0.3, 0. ],
        [0. , 1. , 0. , 0.8, 0.1],
        [0.3, 0.1, 0.1, 0.4, 1. ]],

       [[0.6, 0.3, 0.8, 0.9, 0.6],
        [0.6, 0.2, 0.6, 0.4, 0.1],
        [0.9, 0. , 0.5, 0.8, 0.1]]])

In [51]:
media = np.mean(array11).round(1)
media

0.4

In [55]:
array11_A=np.where(array11 == media, "A", array11)
array11_A

array([[['0.8', 'A', '0.0', '0.3', '0.0'],
        ['0.0', '1.0', '0.0', '0.8', '0.1'],
        ['0.3', '0.1', '0.1', 'A', '1.0']],

       [['0.6', '0.3', '0.8', '0.9', '0.6'],
        ['0.6', '0.2', '0.6', 'A', '0.1'],
        ['0.9', '0.0', '0.5', '0.8', '0.1']]], dtype='<U32')

Si el valor del array es mayor que la media, se reemplaza por "B".

In [47]:
media = np.mean(array11)
media

0.4233333333333334

In [57]:
array11_B=np.where(array11 > media, "B", array11)
array11_B

array([[['B', '0.4', '0.0', '0.3', '0.0'],
        ['0.0', 'B', '0.0', 'B', '0.1'],
        ['0.3', '0.1', '0.1', '0.4', 'B']],

       [['B', '0.3', 'B', 'B', 'B'],
        ['B', '0.2', 'B', '0.4', '0.1'],
        ['B', '0.0', 'B', 'B', '0.1']]], dtype='<U32')

Si el valor del array es menor que la media, se reemplaza por "c".

In [ ]:
array11_C=np.where(array11 < media, "C", array11)
array11_C